"""added fields to base model

Revision ID: af1bfa0f6d9e
Revises: 3dd0fcba30a4
Create Date: 2026-03-14 20:13:40.002417

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1bfa0f6d9e'
down_revision: str | None = '3dd0fcba30a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_url', 'created_at')
    # ### end Alembic commands ###
