"""initial

Revision ID: 3dd0fcba30a4
Revises: 
Create Date: 2025-11-29 22:14:20.428701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd0fcba30a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('short_code', sa.String(length=6), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_url')
    # ### end Alembic commands ###
