"""Initial

Revision ID: b1481881e2ca
Revises: 
Create Date: 2025-11-25 18:48:37.536147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1481881e2ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_u_r_l',
    sa.Column('short_code', sa.String(length=6), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_u_r_l')
    # ### end Alembic commands ###
